# Spring Application Properties
spring.application.name=gymcrm

# PostgreSQL Database Configuration
db.url=jdbc:postgresql://localhost:5432/gymcrm
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver

# Hibernate Configuration
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true
