package com.gymcrm.mapper;

import com.gymcrm.dto.response.TraineeTrainingResponse;
import com.gymcrm.dto.response.TrainerTrainingResponse;
import com.gymcrm.model.Training;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * trainingType (TrainingType → TrainingTypeResponse) is delegated to TrainingTypeMapper.
 * trainerName / traineeName fields are generated by user's firstName + " " + lastName via a MapStruct expression.
 */
@Mapper(componentModel = "spring", uses = {TrainingTypeMapper.class})
public interface TrainingMapper {

    @Mapping(source = "trainingType", target = "trainingType")
    @Mapping(target = "trainerName",
             expression = "java(training.getTrainer().getUser().getFirstName() + \" \" + training.getTrainer().getUser().getLastName())")
    TraineeTrainingResponse toTraineeResponse(Training training);

    @Mapping(source = "trainingType", target = "trainingType")
    @Mapping(target = "traineeName",
             expression = "java(training.getTrainee().getUser().getFirstName() + \" \" + training.getTrainee().getUser().getLastName())")
    TrainerTrainingResponse toTrainerResponse(Training training);
}
